services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: softmind-api:local
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:8080"
    restart: unless-stopped
